name: Publish to Docker Hub

on:
  push:
    branches:
      - madoka
      - mcl

jobs:
  madoka:
    if: github.ref == 'refs/heads/madoka'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: colsrch/madoka:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  mcl:
    if: github.ref == 'refs/heads/mcl'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Init resources
        run: bash ./init.sh
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: colsrch/mcl:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}